package mektup

import (
	"crypto/rand"
	"encoding/binary"
	"fmt"
	"io"
	"strings"
	"time"
)

// ID prefixes used by identifiers generated by Mektup.
const (
	OperationIDPrefix = "op_"
	MessageIDPrefix   = "msg_"
	ReceiptIDPrefix   = "rcpt_"
	EndpointIDPrefix  = "ep_"
	EventIDPrefix     = "evt_"
	StoreIDPrefix     = "store_"
)

// NewUUIDv7 returns a canonical, lower-case UUIDv7 string. UUIDv7 carries the
func NewUUIDv7() string {
	id, err := NewUUIDv7Checked()
	if err != nil {
		panic("mektup: cannot generate collision-resistant UUIDv7: " + err.Error())
	}
	return id
}

// NewUUIDv7Checked is the fail-closed UUIDv7 generator. Callers crossing an
// external reliability boundary should prefer this form over NewUUIDv7.
func NewUUIDv7Checked() (string, error) {
	return NewUUIDv7From(rand.Reader, time.Now())
}

// NewUUIDv7From is deterministic-testable UUIDv7 generation. The reader must
// provide 10 random bytes; its failure is returned rather than degraded.
func NewUUIDv7From(random io.Reader, now time.Time) (string, error) {
	var randomBytes [10]byte
	if _, err := io.ReadFull(random, randomBytes[:]); err != nil {
		return "", fmt.Errorf("read UUID entropy: %w", err)
	}
	var b [16]byte
	ms := uint64(now.UnixMilli())
	b[0] = byte(ms >> 40)
	b[1] = byte(ms >> 32)
	b[2] = byte(ms >> 24)
	b[3] = byte(ms >> 16)
	b[4] = byte(ms >> 8)
	b[5] = byte(ms)
	copy(b[6:], randomBytes[:])
	b[6] = (b[6] & 0x0f) | 0x70
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		binary.BigEndian.Uint32(b[0:4]), binary.BigEndian.Uint16(b[4:6]),
		binary.BigEndian.Uint16(b[6:8]), binary.BigEndian.Uint16(b[8:10]),
		b[10:16]), nil
}

// NewUUIDv7WithEntropy is a descriptive compatibility alias for deterministic
// callers and conformance fixtures.
func NewUUIDv7WithEntropy(random io.Reader, now time.Time) (string, error) {
	return NewUUIDv7From(random, now)
}

// NewPrefixedID creates an immutable Mektup identifier with prefix prefix.
// Prefixes conventionally end in an underscore (for example, "msg_").
func NewPrefixedID(prefix string) string { return prefix + NewUUIDv7() }

func NewPrefixedIDChecked(prefix string) (string, error) {
	uuid, err := NewUUIDv7Checked()
	if err != nil {
		return "", err
	}
	return prefix + uuid, nil
}

func NewOperationID() string { return NewPrefixedID(OperationIDPrefix) }
func NewMessageID() string   { return NewPrefixedID(MessageIDPrefix) }
func NewReceiptID() string   { return NewPrefixedID(ReceiptIDPrefix) }
func NewEndpointID() string  { return NewPrefixedID(EndpointIDPrefix) }
func NewEventID() string     { return NewPrefixedID(EventIDPrefix) }
func NewStoreID() string     { return NewPrefixedID(StoreIDPrefix) }

func NewOperationIDChecked() (string, error) { return NewPrefixedIDChecked(OperationIDPrefix) }
func NewMessageIDChecked() (string, error)   { return NewPrefixedIDChecked(MessageIDPrefix) }
func NewReceiptIDChecked() (string, error)   { return NewPrefixedIDChecked(ReceiptIDPrefix) }
func NewEndpointIDChecked() (string, error)  { return NewPrefixedIDChecked(EndpointIDPrefix) }
func NewEventIDChecked() (string, error)     { return NewPrefixedIDChecked(EventIDPrefix) }
func NewStoreIDChecked() (string, error)     { return NewPrefixedIDChecked(StoreIDPrefix) }

// ValidateID validates a UUIDv7-backed identifier and its required prefix.
func ValidateID(value, prefix string) error {
	if !strings.HasPrefix(value, prefix) {
		return fmt.Errorf("mektup: identifier must start with %q", prefix)
	}
	uuid := strings.TrimPrefix(value, prefix)
	if len(uuid) != 36 || uuid[14] != '7' || uuid[18] != '-' ||
		uuid[8] != '-' || uuid[13] != '-' || uuid[23] != '-' {
		return fmt.Errorf("mektup: invalid UUIDv7 identifier %q", value)
	}
	for i, r := range uuid {
		if i == 8 || i == 13 || i == 18 || i == 23 {
			continue
		}
		if !((r >= '0' && r <= '9') || (r >= 'a' && r <= 'f')) {
			return fmt.Errorf("mektup: invalid UUIDv7 identifier %q", value)
		}
	}
	if uuid[19] < '8' || uuid[19] > 'b' {
		return fmt.Errorf("mektup: invalid UUID variant in %q", value)
	}
	return nil
}

func validOptionalID(value, prefix string) error {
	if value == "" {
		return nil
	}
	return ValidateID(value, prefix)
}
