package mektup

import (
	"crypto/rand"
	"encoding/binary"
	"fmt"
	"strings"
	"sync/atomic"
	"time"
)

// ID prefixes used by identifiers generated by Mektup.
const (
	OperationIDPrefix = "op_"
	MessageIDPrefix   = "msg_"
	ReceiptIDPrefix   = "rcpt_"
	EndpointIDPrefix  = "ep_"
	EventIDPrefix     = "evt_"
	StoreIDPrefix     = "store_"
)

var fallbackCounter uint64

// NewUUIDv7 returns a canonical, lower-case UUIDv7 string. UUIDv7 carries the
// current Unix millisecond timestamp and cryptographically random remainder.
func NewUUIDv7() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		// crypto/rand failure is exceptionally unusual. Keep the API total while
		// retaining uniqueness within this process in the degraded case.
		binary.BigEndian.PutUint64(b[8:], atomic.AddUint64(&fallbackCounter, 1))
	}
	ms := uint64(time.Now().UnixMilli())
	b[0] = byte(ms >> 40)
	b[1] = byte(ms >> 32)
	b[2] = byte(ms >> 24)
	b[3] = byte(ms >> 16)
	b[4] = byte(ms >> 8)
	b[5] = byte(ms)
	b[6] = (b[6] & 0x0f) | 0x70
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		binary.BigEndian.Uint32(b[0:4]), binary.BigEndian.Uint16(b[4:6]),
		binary.BigEndian.Uint16(b[6:8]), binary.BigEndian.Uint16(b[8:10]),
		b[10:16])
}

// NewPrefixedID creates an immutable Mektup identifier with prefix prefix.
// Prefixes conventionally end in an underscore (for example, "msg_").
func NewPrefixedID(prefix string) string { return prefix + NewUUIDv7() }

func NewOperationID() string { return NewPrefixedID(OperationIDPrefix) }
func NewMessageID() string   { return NewPrefixedID(MessageIDPrefix) }
func NewReceiptID() string   { return NewPrefixedID(ReceiptIDPrefix) }
func NewEndpointID() string  { return NewPrefixedID(EndpointIDPrefix) }
func NewEventID() string     { return NewPrefixedID(EventIDPrefix) }
func NewStoreID() string     { return NewPrefixedID(StoreIDPrefix) }

// ValidateID validates a UUIDv7-backed identifier and its required prefix.
func ValidateID(value, prefix string) error {
	if !strings.HasPrefix(value, prefix) {
		return fmt.Errorf("mektup: identifier must start with %q", prefix)
	}
	uuid := strings.TrimPrefix(value, prefix)
	if len(uuid) != 36 || uuid[14] != '7' || uuid[18] != '-' ||
		uuid[8] != '-' || uuid[13] != '-' || uuid[23] != '-' {
		return fmt.Errorf("mektup: invalid UUIDv7 identifier %q", value)
	}
	for i, r := range uuid {
		if i == 8 || i == 13 || i == 18 || i == 23 {
			continue
		}
		if !((r >= '0' && r <= '9') || (r >= 'a' && r <= 'f')) {
			return fmt.Errorf("mektup: invalid UUIDv7 identifier %q", value)
		}
	}
	if uuid[19] < '8' || uuid[19] > 'b' {
		return fmt.Errorf("mektup: invalid UUID variant in %q", value)
	}
	return nil
}

func validOptionalID(value, prefix string) error {
	if value == "" {
		return nil
	}
	return ValidateID(value, prefix)
}
